### PR TITLE
If an invalid number of samples is passed to the sampler, it will go into an infinite loop and crash.

### PR DESCRIPTION
**Pull request by mmcdermott**
This can happen with, for example, mixing up the parameters passed to the binomial sampler.

### CODE REVIEW

**Comment by jacobmenick** [comment]
Thanks for catching this!

**Comment by mmcdermott** [comment]
Thanks for the quick review! Is there any chance you could push a new version of the npm package with this PR in, so we can pull the fix into our App? If not, any idea on when your next release will be?

**Comment by jacobmenick** [comment]
No worries!

Lets ping Will Jones (@wjones127). I don't know the first thing about node
to be honest, and he's the one who put it there.

We haven't really been maintaining this and I don't know if I'd say it's
really been given a proper release FYI. But I imagine Will would be happy
to push these changes to npm.

Cheers,
Jacob

Thanks for the quick review! Is there any chance you could push a new
version of the npm package with this PR in, so we can pull the fix into our
App? If not, any idea on when your next release will be?

**Comment by wjones127** [comment]
Published to npm. Thanks for the PR!

**Comment by mmcdermott** [comment]
Thank you!

**Pull request merged**
